import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By creating an account or using Skorvia (the "Service"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Service.`,
  },
  {
    title: "2. Description of Service",
    content: `Skorvia provides an AI-powered brand credibility analysis platform that generates an Ad Readiness Score, competitor comparisons, and action plans for businesses. The Service is provided on a subscription basis with a free tier and paid plans.`,
  },
  {
    title: "3. Account Registration",
    content: `To access most features, you must create an account by providing a valid email address, name, and password. You must confirm your email address before accessing the dashboard.

You are responsible for maintaining the confidentiality of your password and for all activities under your account. You must notify us immediately of any unauthorized use.`,
  },
  {
    title: "4. Subscription and Payments",
    content: `Paid plans are billed on a monthly or annual basis. Prices are displayed in your local currency at checkout.

• Monthly plans can be cancelled at any time; access continues until the end of the billing period
• Annual plans are non-refundable after 14 days from purchase
• We reserve the right to change prices with 30 days' notice to subscribers
• Failed payments will result in suspension of paid features after a 7-day grace period`,
  },
  {
    title: "5. Acceptable Use",
    content: `You agree not to:
• Use the Service for illegal purposes or to violate any applicable laws
• Submit false or misleading brand information to manipulate scores
• Attempt to reverse-engineer or scrape the Service's AI models
• Use automated scripts to make excessive API requests
• Resell or sublicense access to the Service without written permission`,
  },
  {
    title: "6. Accuracy of Analysis",
    content: `Skorvia's analysis is generated by AI and aggregated data sources. While we strive for accuracy, the Ad Readiness Score and recommendations are provided for informational purposes only.

We make no guarantees that implementing our recommendations will result in profitable advertising campaigns. Marketing outcomes depend on many factors beyond brand credibility.`,
  },
  {
    title: "7. Intellectual Property",
    content: `The Skorvia platform, including its AI models, scoring algorithms, design, and content, is owned by Skorvia and protected by intellectual property laws.

You retain ownership of the brand data you submit. By using the Service, you grant us a limited license to process that data for the purpose of generating your analysis.`,
  },
  {
    title: "8. Limitation of Liability",
    content: `To the fullest extent permitted by law, Skorvia shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including loss of profits or data.

Our total liability to you for any claim shall not exceed the amount you paid us in the 3 months preceding the claim.`,
  },
  {
    title: "9. Termination",
    content: `We may suspend or terminate your account immediately if you violate these Terms. You may delete your account at any time from your profile settings. Upon termination, your data will be deleted within 30 days.`,
  },
  {
    title: "10. Governing Law",
    content: `These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved by arbitration in Lagos, Nigeria under the Lagos State Arbitration Law.`,
  },
  {
    title: "11. Changes to Terms",
    content: `We may update these Terms at any time. We will notify you via email 14 days before material changes take effect. Continued use of the Service after the effective date constitutes acceptance of the new Terms.

For questions: legal@skorvia.io`,
  },
];

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      <main className="flex-1 py-24">
        <div className="container mx-auto px-4 max-w-3xl">
          <div className="mb-12">
            <h1 className="text-4xl font-extrabold tracking-tight mb-4">Terms & Conditions</h1>
            <p className="text-muted-foreground">Last updated: April 5, 2026</p>
          </div>
          <div className="space-y-8">
            <p className="text-muted-foreground text-lg leading-relaxed">
              Please read these Terms carefully before using Skorvia. These Terms constitute a legally binding agreement between you and Skorvia.
            </p>
            {sections.map((section, i) => (
              <div key={i} className="space-y-3">
                <h2 className="text-xl font-bold">{section.title}</h2>
                <p className="text-muted-foreground leading-relaxed whitespace-pre-line">{section.content}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
